server:
  port: 8090

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: none
#        resource.beans.container: org.springframework.orm.hibernate5.SpringBeanContainer # JPA Listener 에서 스프링 Bean DI 하기 위한 설정. (hibernate 5.3+, spring 5.1+)
#        session_factory.session_scoped_interceptor: EntityInterceptor 적용 (hibernate 5.2+)
    open-in-view: false
  h2:
    console:
      enabled: true

# read / write 분리
database:
  datasource-write:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://host:port/schema?useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&autoReconnectForPools=true&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger
    username: coffeenjava
    password: 1234
  datasource-read:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://host:port/schema?useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&autoReconnectForPools=true&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger
    username: coffeenjava
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*" # 모든 actuator기능 open

logging.level:
  org.springframework:
    web: debug
#    orm.jpa: trace # 트랜잭션 로깅
  jdbc: off
  jdbc.sqltiming: info # SQL문과 해당 SQL을 실행시키는데 수행된 시간 정보(milliseconds). sqlonly 설정 포함
#  jdbc.resultsettable: info # 조회 결과
#  jdbc.connection: debug # open&close 정보
#  jdbc.resultset: off # ResultSet을 포함한 모든 JDBC 호출 정보
#  jdbc.audit: off # ResultSet을 제외한 모든 JDBC 호출 정보